import { z } from "zod";

export const SiteSettingsSchema = z.object({
  siteName: z.string().min(1),
  siteDescription: z.string().optional(),
  siteTagline: z.string().optional(),
  bannerURL: z.string().optional(),
  bannerMessage: z.string().optional(),
  logoURL: z.string().optional(),
  backgroundColor: z.string().optional(),
  primaryColor: z.string().optional(),
  secondaryColor: z.string().optional(),
  accentColor: z.string().optional(),
  textColor: z.string().optional(),
  fontSize: z.number().optional(),
  borderRadius: z.number().optional(),
  shadowDepth: z.number().optional(),
  facebookHandle: z.string().optional(),
  twitterHandle: z.string().optional(),
  instagramHandle: z.string().optional(),
  linkedinHandle: z.string().optional(),
  youtubeHandle: z.string().optional(),
  tiktokHandle: z.string().optional(),
  pinterestHandle: z.string().optional(),
  otherSocialHandles: z.array(z.any()).optional(),
  itemsPerPage: z.number().optional(),
  maxCartItems: z.number().optional(),
  enableReviews: z.boolean().optional(),
  enableWishlist: z.boolean().optional(),
  enableGiftCards: z.boolean().optional(),
  enableSubscriptions: z.boolean().optional(),
  defaultCurrency: z.string().optional(),
  taxRate: z.number().optional(),
  freeShippingThreshold: z.number().optional(),
  flatShippingRate: z.number().optional(),
  paymentMethods: z.array(z.string()).optional(),
  defaultShippingMethod: z.string().optional(),
  defaultPaymentMethod: z.string().optional(),
});

export type SiteSettingsFormType = z.infer<typeof SiteSettingsSchema>;
