// This file was auto-generated by prisma-generator-typescript-interfaces

export type UserRole = "USER" | "STAFF" | "ADMIN";

export const UserRole = {
  USER: "USER",
  STAFF: "STAFF",
  ADMIN: "ADMIN",
} satisfies Record<string, UserRole>;

export type OrderStatus =
  | "PENDING"
  | "PAID"
  | "SHIPPED"
  | "DELIVERED"
  | "CANCELLED"
  | "REFUNDED";

export const OrderStatus = {
  PENDING: "PENDING",
  PAID: "PAID",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
  REFUNDED: "REFUNDED",
} satisfies Record<string, OrderStatus>;

export type TransactionStatus = "PENDING" | "PAID" | "REFUNDED" | "FAILED";

export const TransactionStatus = {
  PENDING: "PENDING",
  PAID: "PAID",
  REFUNDED: "REFUNDED",
  FAILED: "FAILED",
} satisfies Record<string, TransactionStatus>;

export type PaymentMethod =
  | "CARD"
  | "STRIPE"
  | "PAYPAL"
  | "SQUARE"
  | "CASH"
  | "APPLE_PAY"
  | "GOOGLE_PAY"
  | "BANK_TRANSFER"
  | "AFTERPAY"
  | "KLARNA"
  | "BITCOIN"
  | "ETHEREUM"
  | "LITECOIN"
  | "OTHER_CRYPTO"
  | "OTHER";

export const PaymentMethod = {
  CARD: "CARD",
  STRIPE: "STRIPE",
  PAYPAL: "PAYPAL",
  SQUARE: "SQUARE",
  CASH: "CASH",
  APPLE_PAY: "APPLE_PAY",
  GOOGLE_PAY: "GOOGLE_PAY",
  BANK_TRANSFER: "BANK_TRANSFER",
  AFTERPAY: "AFTERPAY",
  KLARNA: "KLARNA",
  BITCOIN: "BITCOIN",
  ETHEREUM: "ETHEREUM",
  LITECOIN: "LITECOIN",
  OTHER_CRYPTO: "OTHER_CRYPTO",
  OTHER: "OTHER",
} satisfies Record<string, PaymentMethod>;

export type ShippingCarrier = "UPS" | "FEDEX" | "USPS" | "DHL" | "AMAZON";

export const ShippingCarrier = {
  UPS: "UPS",
  FEDEX: "FEDEX",
  USPS: "USPS",
  DHL: "DHL",
  AMAZON: "AMAZON",
} satisfies Record<string, ShippingCarrier>;

export type ShippingMethod = "STANDARD" | "EXPRESS" | "OVERNIGHT";

export const ShippingMethod = {
  STANDARD: "STANDARD",
  EXPRESS: "EXPRESS",
  OVERNIGHT: "OVERNIGHT",
} satisfies Record<string, ShippingMethod>;

export type ProductStatus = "ACTIVE" | "INACTIVE" | "DISCONTINUED";

export const ProductStatus = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  DISCONTINUED: "DISCONTINUED",
} satisfies Record<string, ProductStatus>;

export type ReviewStatus = "PENDING" | "APPROVED" | "REJECTED";

export const ReviewStatus = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
} satisfies Record<string, ReviewStatus>;

export type DiscountType = "PERCENTAGE" | "FIXED_AMOUNT";

export const DiscountType = {
  PERCENTAGE: "PERCENTAGE",
  FIXED_AMOUNT: "FIXED_AMOUNT",
} satisfies Record<string, DiscountType>;

export type StockMovementType = "SALE" | "RESTOCK" | "ADJUSTMENT";

export const StockMovementType = {
  SALE: "SALE",
  RESTOCK: "RESTOCK",
  ADJUSTMENT: "ADJUSTMENT",
} satisfies Record<string, StockMovementType>;

/**
 * User Model
 */
export interface User {
  id?: string;
  email: string;
  passwordHash: string;
  firstName: string;
  lastName: string;
  phone?: string | null;
  role: UserRole;
  isVerified: boolean;
  lastLogin: Date;
  failedLoginAttempts: number;
  preferences?: JsonValue | null;
  createdAt?: Date;
  updatedAt?: Date;
  addresses?: UserAddress[];
  paymentMethods?: UserPaymentMethod[];
  orders?: Order[];
  reviews?: ProductReview[];
  cart?: Cart | null;
  sessions?: Session[];
}

export interface UserAddress {
  id?: string;
  user?: User;
  userId?: string;
  label: string;
  street: string;
  city: string;
  state: string;
  zip: string;
  country: string;
  isDefault: boolean;
}

export interface UserPaymentMethod {
  id?: string;
  user?: User;
  userId?: string;
  type: PaymentMethod;
  last4: string;
  expiry: string;
  providerToken: string;
}

export interface Collection {
  id?: string;
  name: string;
  slug: string;
  description?: string | null;
  seo?: CollectionSEO | null;
  images?: CollectionImageSet | null;
  createdAt?: Date;
  updatedAt?: Date;
  products?: Product[];
}

export interface Category {
  id?: string;
  name: string;
  slug: string;
  description?: string | null;
  seo?: CollectionSEO | null;
  images?: CollectionImageSet | null;
  createdAt?: Date;
  updatedAt?: Date;
  products?: Product[];
}

export interface CollectionImageSet {
  id?: string;
  collection?: Collection | null;
  collectionId?: string | null;
  category?: Category | null;
  categoryId?: string | null;
  banner: string;
  preview: string;
  thumbnail: string;
}

export interface CollectionSEO {
  id?: string;
  collection?: Collection | null;
  collectionId?: string | null;
  category?: Category | null;
  categoryId?: string | null;
  title?: string | null;
  keywords?: string | null;
}

export interface Product {
  id?: string;
  name: string;
  sku?: string | null;
  price: number;
  discount?: number | null;
  discountType?: DiscountType | null;
  description: string;
  stock?: number | null;
  weight?: number | null;
  reviewCount?: number | null;
  averageRating?: number | null;
  status: ProductStatus;
  dimensions?: ProductDimensions | null;
  tags?: ProductTag[];
  images?: ProductImageSet[];
  options?: ProductOption[];
  variants?: ProductVariant[];
  categories?: Category[];
  collections?: Collection[];
  stockMovements?: StockMovement[];
  reviews?: ProductReview[];
  createdAt?: Date;
  updatedAt?: Date;
  CartItem?: CartItem | null;
}

export interface ProductImageSet {
  id?: string;
  product?: Product;
  productId?: string;
  main: string;
  preview: string;
  thumbnail: string;
}

export interface ProductOption {
  id?: string;
  product?: Product;
  productId?: string;
  name: string;
  values: string[];
}

export interface ProductVariant {
  id?: string;
  product?: Product;
  productId?: string;
  cart?: Cart | null;
  cartId?: string | null;
  options: string[];
  price?: number | null;
  stock?: number | null;
  CartItem?: CartItem | null;
}

export interface ProductDimensions {
  id?: string;
  product?: Product;
  productId?: string;
  weight?: number | null;
  length?: number | null;
  width?: number | null;
  height?: number | null;
}

export interface ProductTag {
  id?: string;
  product?: Product;
  productId?: string;
  name: string;
  color?: string | null;
  textColor?: string | null;
}

export interface ProductReview {
  id?: string;
  product?: Product;
  productId?: string;
  user?: User;
  userId?: string;
  rating: number;
  comment: string;
  status: ReviewStatus;
  helpfulCount: number;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface ProductTagPreset {
  id?: string;
  name: string;
  color?: string | null;
  textColor?: string | null;
}

export interface ProductOptionsPreset {
  id?: string;
  name: string;
  productOptions: ProductOption[];
}

export interface StockMovement {
  id?: string;
  product?: Product;
  productId?: string;
  quantity: number;
  type: StockMovementType;
  timestamp: Date;
  notes?: string | null;
}

export interface Order {
  id?: string;
  user?: User | null;
  userId?: string | null;
  status: OrderStatus;
  total: number;
  tax?: number | null;
  shippingCost?: number | null;
  transaction?: Transaction | null;
  shippingInfo?: OrderShippingInfo | null;
  items?: OrderItem[];
  statusHistory?: OrderStatusHistory[];
  invoices?: Invoice[];
  notes?: string | null;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface OrderItem {
  id?: string;
  order?: Order;
  orderId?: string;
  product: Product
  variant?: ProductVariant;
  quantity: number;
  price: number;
}

export interface Transaction {
  id?: string;
  order?: Order;
  orderId?: string;
  amount: number;
  currency: string;
  method: PaymentMethod;
  status: TransactionStatus;
  billingAddress?: JsonValue | null;
  gatewayResponse?: JsonValue | null;
}

export interface OrderShippingInfo {
  id?: string;
  order?: Order;
  orderId?: string;
  name: string;
  email: string;
  phone: string;
  line1: string;
  line2: string;
  city: string;
  state: string;
  postalCode: string;
  country: string;
  carrier?: ShippingCarrier | null;
  method?: ShippingMethod | null;
  cost?: number | null;
  tracking?: string | null;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface OrderStatusHistory {
  id?: string;
  order?: Order;
  orderId?: string;
  status: OrderStatus;
  timestamp: Date;
}

export interface Invoice {
  id?: string;
  order?: Order;
  orderId?: string;
  invoiceNumber: string;
  pdfUrl?: string | null;
  createdAt?: Date;
}

export interface Coupon {
  id?: string;
  code: string;
  discountType: DiscountType;
  value: number;
  usageLimit?: number | null;
  expiresAt: Date;
  createdAt?: Date;
}

export interface Session {
  id?: string;
  user?: User | null;
  userId?: string | null;
  token: string;
  ipAddress?: string | null;
  userAgent?: string | null;
  cart?: Cart[];
  expiresAt: Date;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface Cart {
  id?: string;
  session?: Session | null;
  sessionId?: string | null;
  user?: User | null;
  userId?: string | null;
  items?: CartItem[];
  subtotal: number;
  total: number;
  createdAt?: Date;
  updatedAt?: Date;
  ProductVariant?: ProductVariant[];
}

export interface CartItem {
  id?: string;
  cart?: Cart;
  cartId?: string;
  product?: Product;
  productId?: string;
  variant?: ProductVariant | null;
  variantId?: string | null;
  quantity: number;
  price: number;
  createdAt?: Date;
  updatedAt?: Date;
}

type JsonValue =
  | string
  | number
  | boolean
  | { [key in string]?: JsonValue }
  | Array<JsonValue>
  | null;
